export const FORM_KEYS = {
  DAO_NAME: 'daoName',
  TOKEN_NAME: 'tokenName',
  TOKEN_SYMBOL: 'tokenSymbol',
  VOTE_TOKEN_TRANSFER: 'votingTransferable',
  NV_TOKEN_TRANSFER: 'nvTransferable',
  QUORUM: 'quorum',
  MIN_RETENTION: 'minRetention',
  SPONSOR_THRESHOLD: 'sponsorThreshold',
  OFFERING: 'newOffering',
  VOTING_PERIOD: 'votingPeriod',
  VOTING_SECONDS: 'votingPeriodInSeconds',
  GRACE_PERIOD: 'gracePeriod',
  GRACE_SECONDS: 'gracePeriodInSeconds',
  SHAMANS: 'shamans',
  MEMBERS: 'members',
};
